AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ndmr API - Backend for DMR codeplug editor

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - production
  JwtSecretKey:
    Type: String
    NoEcho: true
    Description: Secret key for JWT token signing

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.12
    Architectures:
      - arm64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        JWT_SECRET_KEY: !Ref JwtSecretKey
        DYNAMODB_USERS_TABLE: !Ref UsersTable
        DYNAMODB_CODEPLUGS_TABLE: !Ref CodeplugsTable
        AWS_REGION: !Ref AWS::Region

Resources:
  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ndmr-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  CodeplugsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ndmr-codeplugs
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user_id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # Lambda Function
  NdmrApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ndmr-api
      CodeUri: .
      Handler: app.main.handler
      Description: Ndmr API Lambda function
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CodeplugsTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref NdmrHttpApi

  # HTTP API Gateway
  NdmrHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment
      CorsConfiguration:
        AllowOrigins:
          - "http://localhost:*"
          - "https://ndmr.app"
          - "https://*.ndmr.app"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowCredentials: true

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${NdmrHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
  UsersTableName:
    Description: DynamoDB Users table name
    Value: !Ref UsersTable
  CodeplugsTableName:
    Description: DynamoDB Codeplugs table name
    Value: !Ref CodeplugsTable
